# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-05-13 08:45
from __future__ import unicode_literals

import autoplanner.models
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('autoplanner', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='task_serie',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, to='autoplanner.Task'),
        ),
        migrations.AlterField(
            model_name='agentcategorypreferences',
            name='agent',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='autoplanner.Agent'),
        ),
        migrations.AlterField(
            model_name='agentcategorypreferences',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='autoplanner.Category'),
        ),
        migrations.AlterField(
            model_name='agenttaskexclusion',
            name='agent',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='autoplanner.Agent'),
        ),
        migrations.AlterField(
            model_name='agenttaskexclusion',
            name='task',
            field=models.ForeignKey(help_text='Select the task that cannot be performed by the agent.', on_delete=django.db.models.deletion.CASCADE, to='autoplanner.Task', verbose_name='Task'),
        ),
        migrations.AlterField(
            model_name='category',
            name='balancing_tolerance',
            field=models.FloatField(blank=True, default=0.0, null=True, verbose_name='Tolerance for balancing the total duration (in seconds)|tasks across agents'),
        ),
        migrations.AlterField(
            model_name='maxtaskaffectation',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='autoplanner.Category'),
        ),
        migrations.AlterField(
            model_name='maxtimetaskaffectation',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='autoplanner.Category'),
        ),
        migrations.AlterField(
            model_name='organization',
            name='access_token',
            field=models.CharField(default=autoplanner.models.default_token, max_length=300, validators=[django.core.validators.RegexValidator('^[a-zA-Z0-9]{1,300}$')], verbose_name='Access token'),
        ),
        migrations.AlterField(
            model_name='task',
            name='agent',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='autoplanner.Agent'),
        ),
        migrations.AlterField(
            model_name='task',
            name='categories',
            field=models.ManyToManyField(blank=True, db_index=True, to='autoplanner.Category'),
        ),
    ]
