# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-02-19 21:51
from __future__ import unicode_literals

import autoplanner.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('autoplanner', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='agent',
            options={'ordering': ('name',)},
        ),
        migrations.AlterModelOptions(
            name='task',
            options={'ordering': ('start_time', 'end_time')},
        ),
        migrations.AddField(
            model_name='organization',
            name='celery_end',
            field=models.DateTimeField(blank=True, default=None, null=True, verbose_name='Celery end'),
        ),
        migrations.AddField(
            model_name='organization',
            name='celery_start',
            field=models.DateTimeField(blank=True, default=None, null=True, verbose_name='Celery start'),
        ),
        migrations.AddField(
            model_name='organization',
            name='celery_task_id',
            field=models.CharField(blank=True, db_index=True, default=None, max_length=20, null=True, verbose_name='Celery task id'),
        ),
        migrations.AlterField(
            model_name='agent',
            name='name',
            field=models.CharField(db_index=True, max_length=500, verbose_name='Name'),
        ),
        migrations.AlterField(
            model_name='category',
            name='name',
            field=models.CharField(db_index=True, max_length=500, verbose_name='Name'),
        ),
        migrations.AlterField(
            model_name='organization',
            name='name',
            field=models.CharField(db_index=True, max_length=500, verbose_name='Name'),
        ),
        migrations.AlterField(
            model_name='task',
            name='end_time',
            field=models.DateTimeField(db_index=True, default=autoplanner.models.default_day_end, verbose_name='End time'),
        ),
        migrations.AlterField(
            model_name='task',
            name='fixed',
            field=models.BooleanField(db_index=True, default=False, verbose_name='Forced agent'),
        ),
        migrations.AlterField(
            model_name='task',
            name='name',
            field=models.CharField(db_index=True, max_length=500, verbose_name='Name'),
        ),
        migrations.AlterField(
            model_name='task',
            name='start_time',
            field=models.DateTimeField(db_index=True, default=autoplanner.models.default_day_start, verbose_name='Start time'),
        ),
    ]
