# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-07-22 20:29
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('autoplanner', '0002_auto_20170513_1045'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='agent',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, to='autoplanner.Agent'),
        ),
    ]
