# Generated by Django 1.9.2 on 2016-02-22 18:21
from __future__ import unicode_literals

from django.db import migrations
import django.db.models.deletion
import smart_selects.db_fields


class Migration(migrations.Migration):

    dependencies = [
        ('autoplanner', '0003_organization_message'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='category',
            name='parent_category',
        ),
        migrations.AddField(
            model_name='category',
            name='category',
            field=smart_selects.db_fields.ChainedForeignKey(auto_choose=True, blank=True, chained_field='organization', chained_model_field='organization', default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='parent', to='autoplanner.Category', verbose_name='Parent category'),
        ),
        migrations.AlterField(
            model_name='agentcategorypreferences',
            name='agent',
            field=smart_selects.db_fields.ChainedForeignKey(auto_choose=True, blank=True, chained_field='organization', chained_model_field='organization', default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='autoplanner.Agent'),
        ),
        migrations.AlterField(
            model_name='agentcategorypreferences',
            name='category',
            field=smart_selects.db_fields.ChainedForeignKey(auto_choose=True, chained_field='organization', chained_model_field='organization', on_delete=django.db.models.deletion.CASCADE, to='autoplanner.Category'),
        ),
        migrations.AlterField(
            model_name='agenttaskexclusion',
            name='agent',
            field=smart_selects.db_fields.ChainedForeignKey(auto_choose=True, blank=True, chained_field='organization', chained_model_field='organization', default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='autoplanner.Agent'),
        ),
        migrations.AlterField(
            model_name='agenttaskexclusion',
            name='task',
            field=smart_selects.db_fields.ChainedForeignKey(auto_choose=True, blank=True, chained_field='organization', chained_model_field='organization', default=None, help_text='Select the task that cannot be performed by the agent.', null=True, on_delete=django.db.models.deletion.CASCADE, to='autoplanner.Task', verbose_name='Task'),
        ),
        migrations.AlterField(
            model_name='maxtaskaffectation',
            name='category',
            field=smart_selects.db_fields.ChainedForeignKey(auto_choose=True, chained_field='organization', chained_model_field='organization', on_delete=django.db.models.deletion.CASCADE, to='autoplanner.Category'),
        ),
        migrations.AlterField(
            model_name='maxtimetaskaffectation',
            name='category',
            field=smart_selects.db_fields.ChainedForeignKey(auto_choose=True, chained_field='organization', chained_model_field='organization', on_delete=django.db.models.deletion.CASCADE, to='autoplanner.Category'),
        ),
        migrations.AlterField(
            model_name='task',
            name='agent',
            field=smart_selects.db_fields.ChainedForeignKey(auto_choose=True, blank=True, chained_field='organization', chained_model_field='organization', default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='autoplanner.Agent'),
        ),
        migrations.AlterField(
            model_name='task',
            name='category',
            field=smart_selects.db_fields.ChainedForeignKey(auto_choose=True, chained_field='organization', chained_model_field='organization', on_delete=django.db.models.deletion.CASCADE, to='autoplanner.Category'),
        ),
    ]
