# Generated by Django 1.9.2 on 2016-02-22 18:33
from __future__ import unicode_literals

from django.db import migrations
import django.db.models.deletion
import smart_selects.db_fields


class Migration(migrations.Migration):

    dependencies = [
        ('autoplanner', '0004_auto_20160222_1921'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='category',
            name='category',
        ),
        migrations.AddField(
            model_name='category',
            name='parent_category',
            field=smart_selects.db_fields.ChainedForeignKey(auto_choose=True, blank=True, chained_field='organization', chained_model_field='organization', default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='autoplanner.Category', verbose_name='Parent category'),
        ),
    ]
