# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-02-22 18:46
from __future__ import unicode_literals

import autoplanner.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('autoplanner', '0005_auto_20160222_1933'),
    ]

    operations = [
        migrations.AddField(
            model_name='organization',
            name='access_token',
            field=models.CharField(default=autoplanner.models.default_token, max_length=300, verbose_name='Access token'),
        ),
        migrations.AddField(
            model_name='organization',
            name='admins',
            field=models.ManyToManyField(db_index=True, to=settings.AUTH_USER_MODEL),
        ),
    ]
