# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-02-22 18:47
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('autoplanner', '0006_auto_20160222_1946'),
    ]

    operations = [
        migrations.AlterField(
            model_name='organization',
            name='admins',
            field=models.ManyToManyField(db_index=True, to=settings.AUTH_USER_MODEL, verbose_name='Administrators'),
        ),
    ]
