# Generated by Django 1.9.8 on 2016-07-28 10:12
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('autoplanner', '0008_auto_20160405_0835'),
    ]

    operations = [
        migrations.CreateModel(
            name='ScheduleRun',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.NullBooleanField(db_index=True, default=None, verbose_name='Success?')),
                ('message', models.TextField(blank=True, default='', max_length=500, verbose_name='Result message')),
                ('celery_task_id', models.CharField(blank=True, db_index=True, default=None, max_length=20, null=True, verbose_name='Celery task id')),
                ('celery_start', models.DateTimeField(blank=True, default=None, null=True, verbose_name='Celery start')),
                ('celery_end', models.DateTimeField(blank=True, default=None, null=True, verbose_name='Celery end')),
                ('process_id', models.IntegerField(blank=True, db_index=True, default=None, null=True, verbose_name='Process ID')),
                ('result_dict', models.TextField(blank=True, default=None, null=True, verbose_name='JSON-serialized result')),
            ],
        ),
        migrations.AddField(
            model_name='organization',
            name='max_compute_time',
            field=models.PositiveIntegerField(blank=True, default=None, help_text='Leave it blank if you do not want to set a limit', null=True, verbose_name='Maximum time, in seconds, for finding a solution'),
        ),
        migrations.AlterField(
            model_name='agentcategorypreferences',
            name='agent',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='autoplanner.Agent'),
        ),
        migrations.AlterField(
            model_name='agentcategorypreferences',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='autoplanner.Category'),
        ),
        migrations.AlterField(
            model_name='agenttaskexclusion',
            name='agent',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='autoplanner.Agent'),
        ),
        migrations.AlterField(
            model_name='agenttaskexclusion',
            name='task',
            field=models.ForeignKey(help_text='Select the task that cannot be performed by the agent.', on_delete=django.db.models.deletion.CASCADE, to='autoplanner.Task', verbose_name='Task'),
        ),
        migrations.AlterField(
            model_name='maxtaskaffectation',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='autoplanner.Category'),
        ),
        migrations.AlterField(
            model_name='maxtimetaskaffectation',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='autoplanner.Category'),
        ),
        migrations.AlterField(
            model_name='task',
            name='agent',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='autoplanner.Agent'),
        ),
        migrations.AlterField(
            model_name='task',
            name='categories',
            field=models.ManyToManyField(blank=True, db_index=True, to='autoplanner.Category'),
        ),
        migrations.AddField(
            model_name='schedulerun',
            name='organization',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='autoplanner.Organization'),
        ),
    ]
