# Generated by Django 1.9.8 on 2016-07-28 13:46
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('autoplanner', '0009_auto_20160728_1212'),
    ]

    operations = [
        migrations.AddField(
            model_name='organization',
            name='current_schedule',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='current_organizations', to='autoplanner.ScheduleRun'),
        ),
        migrations.AddField(
            model_name='schedulerun',
            name='is_selected',
            field=models.BooleanField(db_index=True, default=False, verbose_name='Selected?'),
        ),
        migrations.AlterField(
            model_name='schedulerun',
            name='celery_end',
            field=models.DateTimeField(blank=True, default=None, null=True, verbose_name='Computation end'),
        ),
        migrations.AlterField(
            model_name='schedulerun',
            name='celery_start',
            field=models.DateTimeField(blank=True, default=None, null=True, verbose_name='Computation start'),
        ),
        migrations.AlterField(
            model_name='schedulerun',
            name='message',
            field=models.TextField(blank=True, default='', max_length=500, verbose_name='Result'),
        ),
        migrations.AlterField(
            model_name='schedulerun',
            name='status',
            field=models.NullBooleanField(db_index=True, default=None, verbose_name='Is valid?'),
        ),
    ]
